name: Build

on:
  push:
    branches: [ master ]
    tags-ignore:
      - "[0-9]+.[0-9]+"
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Maven build
        run: mvn -B install

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build
        run: |
          cd test-server
          docker build -t fluxcapacitorio/flux-capacitor-test:0.002 -t fluxcapacitorio/flux-capacitor-test:latest .
          cd ..

      - name: Push to docker hub
        uses: actions-hub/docker@master
        with:
          args: push fluxcapacitorio/flux-capacitor-test