name: Deploy

on:
  push:
    branches: [ master ]
    tags-ignore:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  BUILD_ENVIRONMENT: github

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Java and Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          server-id: central

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.2
        id: tag_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: minor
          tag_prefix: ""

      - name: Set maven version
        run: |
          mvn -B versions:set -DnewVersion=${{ steps.tag_version.outputs.new_tag }}

      - name: Deploy to Maven Central
        run: mvn -P deploy --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          MAVEN_GPG_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.new_version }}
          name: Flux Capacitor ${{ steps.tag_version.outputs.new_version }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate Flux Host JWT
        id: flux-host-jwt
        uses: ./.github/actions/generate-jwt
        with:
          api-key: ${{ secrets.FLUX_HOST_API_KEY }}

      - name: Log in to Flux Host Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.flux.host
          username: ${{ steps.flux-host-jwt.outputs.userId }}
          password: ${{ steps.flux-host-jwt.outputs.token }}

      - name: Build and push test server docker
        uses: docker/build-push-action@v5
        with:
          context: test-server/.
          push: true
          tags: |
            fluxcapacitorio/flux-capacitor-test:${{ steps.tag_version.outputs.new_version }}
            fluxcapacitorio/flux-capacitor-test:latest

      - name: Build and push proxy docker
        uses: docker/build-push-action@v5
        with:
          context: proxy/.
          push: true
          tags: |
            fluxcapacitorio/flux-capacitor-proxy:${{ steps.tag_version.outputs.new_version }}
            fluxcapacitorio/flux-capacitor-proxy:latest
            registry.flux.host/flux-capacitor-proxy:${{ steps.tag_version.outputs.new_version }}
            registry.flux.host/flux-capacitor-proxy:latest
