name: Deploy any version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version e.g. 1.0.1'
        required: true

env:
  BUILD_ENVIRONMENT: github

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Get version and push tag
        uses: mathieudutour/github-tag-action@v5.6
        id: tag_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: .*
          custom_tag: ${{ github.event.inputs.version }}
          tag_prefix: ""

      - name: Set maven version
        run: |
          mvn -B versions:set -DnewVersion=${{ steps.tag_version.outputs.new_tag }}

      - name: Deploy to Maven Central
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.gpg_private_key }}
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          nexus_username: ${{ secrets.NEXUS_S01_USER }}
          nexus_password: ${{ secrets.NEXUS_S01_PASSWORD }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_version }}
          name: Flux Capacitor ${{ steps.tag_version.outputs.new_version }}
          body: Flux Capacitor ${{ steps.tag_version.outputs.new_version }}

      - name: Build test server docker
        run: |
          cd test-server
          docker build -t fluxcapacitorio/flux-capacitor-test:${{ steps.tag_version.outputs.new_version }} -t fluxcapacitorio/flux-capacitor-test:latest .
          cd ..

      - name: Build proxy docker
        run: |
          cd proxy
          docker build -t fluxcapacitorio/flux-capacitor-proxy:${{ steps.tag_version.outputs.new_version }} -t fluxcapacitorio/flux-capacitor-proxy:latest .
          cd ..

      - name: Push test server to docker hub
        uses: actions-hub/docker@master
        with:
          args: push fluxcapacitorio/flux-capacitor-test

      - name: Push proxy to docker hub
        uses: actions-hub/docker@master
        with:
          args: push fluxcapacitorio/flux-capacitor-proxy