name: Publish javadoc

on:
  workflow_dispatch:

env:
  BUILD_ENVIRONMENT: github

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Java and Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Generate javadoc html
        run: mvn -B site

      - name: Move per-module sites
        run: |
          for module in java-client common proxy test-server; do
            mkdir -p target/site/$module
            mv $module/target/site/* target/site/$module/
          done

      - name: Publish Javadoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site
          destination_dir: javadoc