name: Build PR

on:
  pull_request:
    branches: [ master ]

env:
  BUILD_ENVIRONMENT: github

jobs:
  build-pr:
    runs-on: ubuntu-latest
    ports:
      - 8080:8080
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Maven build
        run: mvn -B install