name: Build PR

on:
  pull_request:
    branches: [ master ]

env:
  BUILD_ENVIRONMENT: github

jobs:
  build-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Java and Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Run Maven build
        run: mvn -B install